### ISSUE TITLE
Add contact section

### ISSUE THREAD

**Issue by lilianabounegru** [PublicDataLab/fake-news-website#6]
Add contact section after 'Featured on' section with the following text:

Contact
Please direct any inquires about this project to the co-investigators (Liliana Bounegru, Jonathan Gray, Tommaso Venturini and Michele Mauri) at fakenews[at]publicdatalab.org.

@jwyg Is this the right email address to provide for inquires about the guide?

**Comment by jwyg** [comment]
Yes that is correct!
